name: Content build check

on:
  pull_request:
    paths-ignore:
      - rmotw/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: sudo npm install -g sass && pip install -r requirements.txt
      - name: Build documents
        run: make html