name: Content Build (draft)

on:
  push:
    branches: [ draft ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: sudo npm install -g sass && pip install -r requirements.txt
      - name: Build documents
        run: make html
      - name: Compress output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r draft-output.zip output
      - uses: actions/upload-artifact@v2
        with:
          name: draft-output
          path: draft-output.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: draft-output
      - name: Draft release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: draft
          prerelease: true
          draft: true
          files: draft-output.zip