name: Check RMOTW draft

on:
  push:
    branches: [ draft ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: List files
        run: echo $PWD && ls -la
      - name: Build MOTW docs
        run: docker run --rm -v ${{ github.workspace }}:/home/app/pdock:rw slyons/pelican-docker:latest ls -la && make publish