name: Draft content build

on:
  push:
    branches: [ draft ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install sass
        run: sudo npm install -g sass
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Build documents
        run: make html