name: Check RMOTW draft

on:
  push:
    branches: [ draft ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: slyons/pelican-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: List files
        run: echo $PWD && ls -la
      - name: Build MOTW docs
        run: mkdir output && make dockerpub