name: Content Build (draft)

on:
  push:
    branches: [ draft ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: sudo npm install -g sass && pip install -r requirements.txt
      - name: Build documents
        run: make html
      - name: Draft release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          draft: true
          files: |
            output/**