name: Build RMOTW

on:
  push:
    pull_request: [ main ]
    paths:
      - 'content/**'
      - 'themes/**'
      - 'pelicanconf.py'
      - 'publish.conf'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - name: Build MOTW docs
      run: make dockerpub
    - name: Publish docs
      run: make github