name: Content Build (main)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - rmotw/**

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: sudo npm install -g sass && pip install -r requirements.txt
      - name: Public release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          files: |
            output/**
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: output
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll