name: Rust examples

on:
  push:
    branches: [ draft, main ]
    paths-ignore:
      - '!rmotw/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '!rmotw/**'
      - '.github/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: make cargoclippy
    - name: Run tests
      run: make cargotest
