name: Rust examples

on:
  push:
    branches: [ draft ]
    paths:
      - 'rmotw/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'rmotw/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: make cargoclippy
    - name: Run tests
      run: make cargotest
